### ISSUE TITLE
`getPermissionState()` is incorrect for [deny & don't ask again]

### ISSUE THREAD

**Issue by jacobras** [icerockdev/moko-permissions#104]
The method `permissionController.getPermissionState()` returns an incorrect state on Android when using [deny & don't ask again]:

* The first time, `getPermissionState()` returns `PermissionState.NotDetermined` ✅
* After [deny], `getPermissionState()` returns `PermissionState.Denied` ✅
* After [deny & don't ask again], `getPermissionState()` returns `PermissionState.NotDetermined` ❌

⏩ The `NotDetermined` state is not always accurate on Android.

## Reproduction code

Reproduction repository: https://github.com/jacobras/Moko-Permissions-Android-Bug

## Screen capture

![MokoPermissionStateBugAndroid](https://github.com/icerockdev/moko-permissions/assets/3338890/06bf6a5f-2f0f-4364-ab78-c500ede43aed)

**Comment by Alex009** [comment]
will be released in 0.18.0
