### ISSUE TITLE
KMM Compose Android Error: "ClassCastException: com.example.app.MainActivity cannot be cast to androidx.fragment.app.FragmentActivity"

### ISSUE THREAD

**Issue by Stonerub** [icerockdev/moko-permissions#106]
Hi, got issue in kmm compose, on android, BindEffect() call this exception:
`ClassCastException: com.example.app.MainActivity cannot be cast to androidx.fragment.app.FragmentActivity`

iOS works great, without errors. My compose code:

```
    val factory: PermissionsControllerFactory = rememberPermissionsControllerFactory()

    val viewModel = getViewModel(
        key = "app viewModel",
        factory = viewModelFactory { AppViewModel(
            databaseDriverFactory,
            factory.createPermissionsController()
        ) }
    )

    BindEffect(viewModel.permissionsController)
```

Using moko mvvm. ViewModel permission calling:
```
init {
        viewModelScope.launch {
            permissionsController.providePermission(Permission.REMOTE_NOTIFICATION)
        }
}
```

**Comment by Tingel24** [comment]
I have the same problem

**Comment by mojtaba-amiri** [comment]
Apparently it's about the MainActivity being `ComponentActivity` and not `FragmentActivity`. Changing it to FragmentActivity would be a workaround until Moko team fixes the issue.

**Comment by Stonerub** [comment]
> Apparently it's about the MainActivity being `ComponentActivity` and not `FragmentActivity`. Changing it to FragmentActivity would be a workaround until Moko team fixes the issue.

Thank's, it work for me

**Comment by ZiXOps** [comment]
For now developer must use `FragmentActivity` as root activity to be able display permission dialogs with `fragmentManager`. I think in future we can change request permissons approach to `rememberLauncherForActivityResult` for compose apps.
