### ISSUE TITLE
Cannot open settings in iOS 18

### ISSUE THREAD

**Issue by m120786** [icerockdev/moko-permissions#128]
with the iOS 18, we can no longer do `openAppSettings()`, it gives this error: BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO). (running it on emulator using XCode 16)

**Comment by marcelpallares** [comment]
Same issue here!

**Comment by raheemadamboev** [comment]
Same issue!
