### ISSUE TITLE
Could not resolve dev.icerock.moko:permissions:0.18.0.

### ISSUE THREAD

**Issue by shalva97** [icerockdev/moko-permissions#130]
Hi. I have added your lib to my project and it worked. Few days later reopened the project and it fails to resolve the lib.

![Screenshot 2024-09-25 at 03 10 52](https://github.com/user-attachments/assets/5a40f6df-004e-4fd5-affc-ae71e36d6177)

Maybe this will also be useful

![Screenshot 2024-09-25 at 03 12 06](https://github.com/user-attachments/assets/fdf9a1fa-b011-4e61-b656-1c0e63845907)

My guess is that it fails when downloading dependency of permissions lib. Those urls return error status code

https://dl.google.com/dl/android/maven2/androidx/core/core-ktx/android-core/core-ktx-android-core.pom

https://repo.maven.apache.org/maven2/androidx/core/core-ktx/android-core/core-ktx-android-core.pom

**Comment by Alex009** [comment]
moko-permissions not support "desktop" target (i think it's jvm). supported only android & ios

**Comment by shalva97** [comment]
ahh fk, did not look at the error message fully...
