### ISSUE TITLE
Android. Empty grantResults array is not consumed.

### ISSUE THREAD

**Issue by qwert2603** [icerockdev/moko-permissions#30]
Hello! According to docs of `Fragment.onRequestPermissionsResult`:
```
It is possible that the permissions request interaction with the user is interrupted.
In this case you will receive empty permissions and results arrays which should be treated as a cancellation.
```
But method [`ResolverFragment.onRequestPermissionsResult`](https://github.com/icerockdev/moko-permissions/blob/77a6d96be605d4fe97f189703f605f7f4f660584/permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsController.kt#L121) does not consume that case.

**Comment by Alex009** [comment]
will be in 0.8.0
