### ISSUE TITLE
How to use with jetpack compose and native  view model?

### ISSUE THREAD

**Issue by Kashif-E** [icerockdev/moko-permissions#53]
I  have a jetpack compose KMM app and I don't have access to support fragment manager. Is there a way to use Mono Permissions with these components?

**Comment by Alex009** [comment]
for now you can use this workaround:
```
val context: Context = LocalContext.current
val activity: ComponentActivity = context as! FragmentActivity // your activity should be AppCompatActivity
val fragmentManager: FragmentManager = activity.supportFragmentManager
```

later we add direct support of compose
