### ISSUE TITLE
Missing authorization status checks for iOS remote notifications

### ISSUE THREAD

**Issue by ztepsa** [icerockdev/moko-permissions#63]
There's an issue in the `getPermissionState` function for iOS remote notifications where it throws exception in case of `UNAuthorizationStatusProvisional` and `UNAuthorizationStatusEphemeral` which both provide ability to receive notifications.

Here's info from Apple docs
> [UNAuthorizationStatusProvisional](https://developer.apple.com/documentation/usernotifications/unauthorizationstatus/provisional) - The application is provisionally authorized to post noninterruptive user notifications.
> [UNAuthorizationStatusEphemeral](https://developer.apple.com/documentation/usernotifications/unauthorizationstatus/ephemeral) - The app is authorized to schedule or receive notifications for a limited amount of time.

When checking status library should return `PermissionState.Granted` for these two statuses.
```kotlin
override suspend fun getPermissionState(): PermissionState {
    // removed code for clarity
    return when (status) {
        UNAuthorizationStatusAuthorized -> PermissionState.Granted
        UNAuthorizationStatusNotDetermined -> PermissionState.NotDetermined
        UNAuthorizationStatusDenied -> PermissionState.DeniedAlways
        else -> throw IllegalStateException("unknown push authorization status $status")
    }
}
```

**Comment by Alex009** [comment]
will be released in 0.15.0
