### ISSUE TITLE
Cannot find 'PermissionsController' in scope

### ISSUE THREAD

**Issue by pauminku** [icerockdev/moko-permissions#65]
I added moko-permissions library to my shared KMM module and Android module and it's working fine.
But when I'm trying to add it to the iOS project I get this error whenever I want to create the `PermissionsController()`:

`Cannot find 'PermissionsController' in scope`

I'm pretty sure I added the proper import. Also I reviewed the Sample and I'm not seeing any difference.
Any idea of what I'm leaving out?
Thanks

**Comment by Alex009** [comment]
@pauminku hi.
you should add library to `export` in framework binary

**Comment by pauminku** [comment]
Thanks Alex for your quick response and for your work in these amazing libraries.

I'm not sure I'm getting your point. Are you talking about `Podfile` or `build.gradle`or an XCode configuration?

I'm already using the KMM shared library in my iOS app, I have access to all my shared classes, like ViewModels, Repositories, etc. event I have access to `PermissionsPermissionsControllerProtocol` but I don't see a way to create an instance of it in my iOS code.
![Captura de Pantalla 2022-11-23 a les 18 31 53](https://user-images.githubusercontent.com/24522576/203611993-9d13b00f-dfba-4f5c-a6fa-013ac0d2bb05.jpg)
